const SPOLKI = [
  { symbol: "PKO.WA", nazwa: "PKO Bank Polski", gielda: "GPW" },
  { symbol: "PZU.WA", nazwa: "PZU", gielda: "GPW" },
  { symbol: "PKN.WA", nazwa: "Orlen", gielda: "GPW" },
  { symbol: "PEO.WA", nazwa: "Bank Pekao", gielda: "GPW" },
  { symbol: "SPL.WA", nazwa: "Santander Bank Polska", gielda: "GPW" },
  { symbol: "MBK.WA", nazwa: "mBank", gielda: "GPW" },
  { symbol: "ING.WA", nazwa: "ING Bank Śląski", gielda: "GPW" },
  { symbol: "ALR.WA", nazwa: "Alior Bank", gielda: "GPW" },
  { symbol: "MIL.WA", nazwa: "Bank Millennium", gielda: "GPW" },
  { symbol: "KGH.WA", nazwa: "KGHM", gielda: "GPW" },
  { symbol: "JSW.WA", nazwa: "JSW", gielda: "GPW" },
  { symbol: "CDR.WA", nazwa: "CD Projekt", gielda: "GPW" },
  { symbol: "ALE.WA", nazwa: "Allegro", gielda: "GPW" },
  { symbol: "LPP.WA", nazwa: "LPP", gielda: "GPW" },
  { symbol: "DNP.WA", nazwa: "Dino Polska", gielda: "GPW" },
  { symbol: "ZAB.WA", nazwa: "Zabka Group", gielda: "GPW" },
  { symbol: "KRU.WA", nazwa: "Kruk", gielda: "GPW" },
  { symbol: "CPS.WA", nazwa: "Cyfrowy Polsat", gielda: "GPW" },
  { symbol: "OPL.WA", nazwa: "Orange Polska", gielda: "GPW" },
  { symbol: "PCO.WA", nazwa: "Pepco Group", gielda: "GPW" },
  { symbol: "BDX.WA", nazwa: "Budimex", gielda: "GPW" },
  { symbol: "KTY.WA", nazwa: "Grupa Kęty", gielda: "GPW" },
  { symbol: "ACP.WA", nazwa: "Asseco Poland", gielda: "GPW" },
  { symbol: "TEN.WA", nazwa: "Ten Square Games", gielda: "GPW" },
  { symbol: "11B.WA", nazwa: "11 bit studios", gielda: "GPW" },
  { symbol: "XTB.WA", nazwa: "XTB", gielda: "GPW" },
  { symbol: "CCC.WA", nazwa: "CCC", gielda: "GPW" },
  { symbol: "ATT.WA", nazwa: "Grupa Azoty", gielda: "GPW" },
  { symbol: "PGE.WA", nazwa: "PGE", gielda: "GPW" },
  { symbol: "TPE.WA", nazwa: "Tauron", gielda: "GPW" },
  { symbol: "ENA.WA", nazwa: "Enea", gielda: "GPW" },
  { symbol: "LWB.WA", nazwa: "Bogdanka", gielda: "GPW" },
  { symbol: "MRC.WA", nazwa: "Mercator Medical", gielda: "GPW" },
  { symbol: "WIG20.WA", nazwa: "WIG20 (indeks)", gielda: "GPW" },

  { symbol: "JPM", nazwa: "JPMorgan Chase", gielda: "NYSE" },
  { symbol: "V", nazwa: "Visa", gielda: "NYSE" },
  { symbol: "MA", nazwa: "Mastercard", gielda: "NYSE" },
  { symbol: "JNJ", nazwa: "Johnson & Johnson", gielda: "NYSE" },
  { symbol: "WMT", nazwa: "Walmart", gielda: "NYSE" },
  { symbol: "XOM", nazwa: "Exxon Mobil", gielda: "NYSE" },
  { symbol: "CVX", nazwa: "Chevron", gielda: "NYSE" },
  { symbol: "BAC", nazwa: "Bank of America", gielda: "NYSE" },
  { symbol: "GS", nazwa: "Goldman Sachs", gielda: "NYSE" },
  { symbol: "KO", nazwa: "Coca-Cola", gielda: "NYSE" },
  { symbol: "PEP", nazwa: "PepsiCo", gielda: "NYSE" },
  { symbol: "DIS", nazwa: "Walt Disney", gielda: "NYSE" },
  { symbol: "GE", nazwa: "GE Aerospace", gielda: "NYSE" },
  { symbol: "BA", nazwa: "Boeing", gielda: "NYSE" },
  { symbol: "IBM", nazwa: "IBM", gielda: "NYSE" },
  { symbol: "CAT", nazwa: "Caterpillar", gielda: "NYSE" },
  { symbol: "HD", nazwa: "Home Depot", gielda: "NYSE" },
  { symbol: "PG", nazwa: "Procter & Gamble", gielda: "NYSE" },
  { symbol: "UNH", nazwa: "UnitedHealth", gielda: "NYSE" },
  { symbol: "NKE", nazwa: "Nike", gielda: "NYSE" },
  { symbol: "MRK", nazwa: "Merck", gielda: "NYSE" },
  { symbol: "SPY", nazwa: "SPDR S&P 500 ETF", gielda: "NYSE" },

  { symbol: "AAPL", nazwa: "Apple", gielda: "NASDAQ" },
  { symbol: "MSFT", nazwa: "Microsoft", gielda: "NASDAQ" },
  { symbol: "NVDA", nazwa: "NVIDIA", gielda: "NASDAQ" },
  { symbol: "GOOGL", nazwa: "Alphabet (Google)", gielda: "NASDAQ" },
  { symbol: "AMZN", nazwa: "Amazon", gielda: "NASDAQ" },
  { symbol: "META", nazwa: "Meta Platforms", gielda: "NASDAQ" },
  { symbol: "TSLA", nazwa: "Tesla", gielda: "NASDAQ" },
  { symbol: "NFLX", nazwa: "Netflix", gielda: "NASDAQ" },
  { symbol: "AMD", nazwa: "AMD", gielda: "NASDAQ" },
  { symbol: "INTC", nazwa: "Intel", gielda: "NASDAQ" },
  { symbol: "AVGO", nazwa: "Broadcom", gielda: "NASDAQ" },
  { symbol: "COST", nazwa: "Costco", gielda: "NASDAQ" },
  { symbol: "ADBE", nazwa: "Adobe", gielda: "NASDAQ" },
  { symbol: "CSCO", nazwa: "Cisco", gielda: "NASDAQ" },
  { symbol: "PEP", nazwa: "PepsiCo", gielda: "NASDAQ" },
  { symbol: "QCOM", nazwa: "Qualcomm", gielda: "NASDAQ" },
  { symbol: "AMAT", nazwa: "Applied Materials", gielda: "NASDAQ" },
  { symbol: "SBUX", nazwa: "Starbucks", gielda: "NASDAQ" },
  { symbol: "PYPL", nazwa: "PayPal", gielda: "NASDAQ" },
  { symbol: "QQQ", nazwa: "Invesco QQQ ETF", gielda: "NASDAQ" }
];
